"""
Student Grade Management System
Single-file, console-based Python application implementing the full system described
in the uploaded requirements document.

Features implemented:
- Student CRUD (create, read/search, update, delete [soft/hard])
- Grade CRUD (add, view, update, delete)
- GPA/CGPA/subject average calculations
- Reports: individual, class, subject, semester
- File persistence: students.txt, grades.txt (pipe-delimited)
- Excel import/export using openpyxl
- Backups before write operations
- Basic performance-conscious design (lists + index maps)
- Validation and error handling

Dependencies: openpyxl
Install: pip install openpyxl

Author: Generated by ChatGPT for user request "full system"
"""

import os
import sys
import shutil
import datetime
import re
from collections import defaultdict
from copy import deepcopy

try:
    import openpyxl
    from openpyxl import Workbook
except Exception:
    openpyxl = None

# -----------------------------
# Configuration / Filenames
# -----------------------------
STUDENTS_FILE = 'students.txt'
GRADES_FILE = 'grades.txt'
DELETION_LOG = 'deletion_log.txt'
BACKUP_DIR = 'backups'

DATE_FORMAT = '%d/%m/%Y'
STU_ID_PATTERN = re.compile(r'^STU\d{3}$')
EMAIL_PATTERN = re.compile(r'^[^@\s]+@[^@\s]+\.[^@\s]+$')

# -----------------------------
# Data containers
# -----------------------------
all_students = []  # list of student dicts
all_grades = []    # list of grade dicts

# Quick lookup maps for performance
student_index = {}  # student_id -> index in all_students
email_index = {}    # email -> student_id

# -----------------------------
# Utility functions
# -----------------------------

def ensure_files():
    os.makedirs(BACKUP_DIR, exist_ok=True)
    for fname in (STUDENTS_FILE, GRADES_FILE, DELETION_LOG):
        if not os.path.exists(fname):
            with open(fname, 'w', encoding='utf-8') as f:
                f.write('')


def backup_file(filename):
    if not os.path.exists(filename):
        return
    ts = datetime.datetime.now().strftime('%Y%m%d_%H%M%S')
    dest = os.path.join(BACKUP_DIR, f'{filename}_{ts}.bak')
    shutil.copy2(filename, dest)


# -----------------------------
# Validation functions
# -----------------------------

def validate_student_id(student_id):
    return bool(STU_ID_PATTERN.match(student_id))


def validate_email(email):
    return bool(EMAIL_PATTERN.match(email))


def parse_date(date_string):
    try:
        return datetime.datetime.strptime(date_string, DATE_FORMAT).date()
    except Exception:
        return None


def calculate_age(dob_date):
    today = datetime.date.today()
    years = today.year - dob_date.year - ((today.month, today.day) < (dob_date.month, dob_date.day))
    return years


def validate_marks(marks, max_marks):
    try:
        m = float(marks)
        M = float(max_marks)
    except Exception:
        return False
    if m < 0 or m > M:
        return False
    return True

# -----------------------------
# File I/O (pipe-delimited)
# -----------------------------

def load_students_from_file(filename=STUDENTS_FILE):
    global all_students, student_index, email_index
    all_students = []
    student_index = {}
    email_index = {}
    if not os.path.exists(filename):
        return
    with open(filename, 'r', encoding='utf-8') as f:
        for i, line in enumerate(f):
            line = line.strip()
            if not line:
                continue
            parts = line.split('|')
            if len(parts) < 8:
                continue
            sid, first, last, email, dob, program, enroll_year, status = parts[:8]
            try:
                enroll_year = int(enroll_year)
            except Exception:
                enroll_year = None
            student = {
                'student_id': sid,
                'first_name': first,
                'last_name': last,
                'email': email,
                'dob': dob,
                'program': program,
                'enrollment_year': enroll_year,
                'status': status
            }
            all_students.append(student)
            student_index[sid] = len(all_students) - 1
            email_index[email.lower()] = sid


def save_students_to_file(filename=STUDENTS_FILE):
    backup_file(filename)
    with open(filename, 'w', encoding='utf-8') as f:
        for s in all_students:
            line = '|'.join([
                s.get('student_id',''),
                s.get('first_name',''),
                s.get('last_name',''),
                s.get('email',''),
                s.get('dob',''),
                s.get('program',''),
                str(s.get('enrollment_year','')),
                s.get('status','')
            ])
            f.write(line + '\n')


def load_grades_from_file(filename=GRADES_FILE):
    global all_grades
    all_grades = []
    if not os.path.exists(filename):
        return
    with open(filename, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            parts = line.split('|')
            if len(parts) < 7:
                continue
            sid, subject, atype, marks_obtained, maximum_marks, date, semester = parts[:7]
            try:
                marks_obtained = float(marks_obtained)
                maximum_marks = float(maximum_marks)
            except Exception:
                continue
            grade = {
                'student_id': sid,
                'subject': subject,
                'assessment_type': atype,
                'marks_obtained': marks_obtained,
                'maximum_marks': maximum_marks,
                'date': date,
                'semester': semester
            }
            all_grades.append(grade)


def save_grades_to_file(filename=GRADES_FILE):
    backup_file(filename)
    with open(filename, 'w', encoding='utf-8') as f:
        for g in all_grades:
            line = '|'.join([
                g.get('student_id',''),
                g.get('subject',''),
                g.get('assessment_type',''),
                f"{g.get('marks_obtained',0):.2f}",
                f"{g.get('maximum_marks',0):.2f}",
                g.get('date',''),
                g.get('semester','')
            ])
            f.write(line + '\n')

# -----------------------------
# Student Management Functions
# -----------------------------

def generate_next_student_id():
    # find max existing numeric portion
    maxn = 0
    for s in all_students:
        sid = s['student_id']
        try:
            n = int(sid.replace('STU',''))
            if n > maxn:
                maxn = n
        except Exception:
            continue
    return f"STU{maxn+1:03d}"


def add_student(student_data):
    sid = student_data.get('student_id')
    email = student_data.get('email','').lower()
    if not sid:
        sid = generate_next_student_id()
        student_data['student_id'] = sid
    if sid in student_index:
        raise ValueError('Student ID already exists')
    if email and email in email_index:
        raise ValueError('Email already exists')
    # Validate
    if not validate_student_id(sid):
        raise ValueError('Invalid student ID format')
    if 'dob' not in student_data or not parse_date(student_data['dob']):
        raise ValueError('Invalid DOB format')
    dob_parsed = parse_date(student_data['dob'])
    age = calculate_age(dob_parsed)
    if age < 16 or age > 100:
        raise ValueError('Age must be between 16 and 100')
    if email and not validate_email(email):
        raise ValueError('Invalid email format')
    student = {
        'student_id': sid,
        'first_name': student_data.get('first_name','').strip(),
        'last_name': student_data.get('last_name','').strip(),
        'email': student_data.get('email','').strip(),
        'dob': student_data.get('dob','').strip(),
        'program': student_data.get('program','').strip(),
        'enrollment_year': int(student_data.get('enrollment_year') or 0),
        'status': student_data.get('status','Active')
    }
    all_students.append(student)
    student_index[sid] = len(all_students)-1
    if student['email']:
        email_index[student['email'].lower()] = sid
    save_students_to_file()
    return sid


def search_student_by_id(student_id):
    idx = student_index.get(student_id)
    if idx is None:
        return None
    return deepcopy(all_students[idx])


def update_student(student_id, update_data):
    idx = student_index.get(student_id)
    if idx is None:
        raise ValueError('Student not found')
    student = all_students[idx]
    # Only updatable fields: email, program, status
    new_email = update_data.get('email')
    if new_email:
        if not validate_email(new_email):
            raise ValueError('Invalid email format')
        if new_email.lower() != student.get('email','').lower() and new_email.lower() in email_index:
            raise ValueError('Email already exists')
    if 'program' in update_data:
        student['program'] = update_data['program']
    if new_email:
        # update index
        old = student.get('email','').lower()
        if old in email_index:
            del email_index[old]
        student['email'] = new_email
        email_index[new_email.lower()] = student_id
    if 'status' in update_data:
        student['status'] = update_data['status']
    save_students_to_file()
    return True


def delete_student(student_id, hard=False):
    idx = student_index.get(student_id)
    if idx is None:
        raise ValueError('Student not found')
    student = all_students[idx]
    # Log deletion
    with open(DELETION_LOG, 'a', encoding='utf-8') as f:
        f.write(f"{datetime.datetime.now().isoformat()}|{student_id}|{'HARD' if hard else 'SOFT'}|{student}\n")
    if hard:
        # remove student and associated grades
        del all_students[idx]
        # rebuild student_index and email_index
        rebuild_student_indices()
        # remove grades
        global all_grades
        all_grades = [g for g in all_grades if g['student_id'] != student_id]
        save_grades_to_file()
    else:
        student['status'] = 'Inactive'
        save_students_to_file()
    return True


def rebuild_student_indices():
    global student_index, email_index
    student_index = {}
    email_index = {}
    for i, s in enumerate(all_students):
        student_index[s['student_id']] = i
        if s.get('email'):
            email_index[s['email'].lower()] = s['student_id']

# -----------------------------
# Grade Management
# -----------------------------

def add_grade(grade_data):
    sid = grade_data.get('student_id')
    if sid not in student_index:
        raise ValueError('Student does not exist')
    marks = float(grade_data.get('marks_obtained'))
    maxm = float(grade_data.get('maximum_marks', 100))
    if not validate_marks(marks, maxm):
        raise ValueError('Invalid marks')
    g = {
        'student_id': sid,
        'subject': grade_data.get('subject','').strip(),
        'assessment_type': grade_data.get('assessment_type','').strip(),
        'marks_obtained': float(marks),
        'maximum_marks': float(maxm),
        'date': grade_data.get('date','').strip(),
        'semester': grade_data.get('semester','').strip()
    }
    all_grades.append(g)
    save_grades_to_file()
    return True


def get_student_grades(student_id):
    return [deepcopy(g) for g in all_grades if g['student_id'] == student_id]


def update_grade(student_id, subject, assessment_type, update_data):
    updated = False
    for g in all_grades:
        if g['student_id'] == student_id and g['subject'] == subject and g['assessment_type'] == assessment_type:
            if 'marks_obtained' in update_data:
                if not validate_marks(update_data['marks_obtained'], g['maximum_marks']):
                    raise ValueError('Invalid marks')
                g['marks_obtained'] = float(update_data['marks_obtained'])
            if 'maximum_marks' in update_data:
                g['maximum_marks'] = float(update_data['maximum_marks'])
            if 'date' in update_data:
                g['date'] = update_data['date']
            if 'semester' in update_data:
                g['semester'] = update_data['semester']
            updated = True
    if updated:
        save_grades_to_file()
    return updated


def delete_grade(student_id, subject, assessment_type):
    global all_grades
    before = len(all_grades)
    all_grades = [g for g in all_grades if not (g['student_id']==student_id and g['subject']==subject and g['assessment_type']==assessment_type)]
    if len(all_grades) < before:
        save_grades_to_file()
        return True
    return False

# -----------------------------
# Calculations & Grading
# -----------------------------

def calculate_percentage(marks_obtained, maximum_marks):
    if maximum_marks == 0:
        return 0.0
    return (marks_obtained / maximum_marks) * 100.0


def get_letter_grade(percentage):
    p = percentage
    if p >= 90:
        return 'A+'
    if p >= 85:
        return 'A'
    if p >= 80:
        return 'B+'
    if p >= 75:
        return 'B'
    if p >= 70:
        return 'C+'
    if p >= 65:
        return 'C'
    if p >= 60:
        return 'D'
    return 'F'


def grade_point(letter):
    mapping = {
        'A+':4.0,'A':3.7,'B+':3.3,'B':3.0,'C+':2.7,'C':2.3,'D':2.0,'F':0.0
    }
    return mapping.get(letter, 0.0)


def calculate_subject_average(student_id, subject):
    rows = [g for g in all_grades if g['student_id']==student_id and g['subject']==subject]
    if not rows:
        return None
    sum_marks = sum(g['marks_obtained'] for g in rows)
    sum_max = sum(g['maximum_marks'] for g in rows)
    if sum_max == 0:
        return 0.0
    return (sum_marks / sum_max) * 100.0


def calculate_semester_gpa(student_id, semester):
    rows = [g for g in all_grades if g['student_id']==student_id and g['semester']==semester]
    if not rows:
        return None
    grade_points = []
    # For calculation, average each subject's percentage across assessments
    subj_map = defaultdict(lambda: {'marks':0.0,'max':0.0})
    for g in rows:
        subj_map[g['subject']]['marks'] += g['marks_obtained']
        subj_map[g['subject']]['max'] += g['maximum_marks']
    for subj, vals in subj_map.items():
        pct = calculate_percentage(vals['marks'], vals['max'])
        letter = get_letter_grade(pct)
        gp = grade_point(letter)
        grade_points.append(gp)
    if not grade_points:
        return 0.0
    return sum(grade_points) / len(grade_points)


def calculate_cgpa(student_id):
    # average of semester GPAs
    semesters = set(g['semester'] for g in all_grades if g['student_id']==student_id)
    if not semesters:
        return None
    gpas = []
    for sem in semesters:
        gpa = calculate_semester_gpa(student_id, sem)
        if gpa is not None:
            gpas.append(gpa)
    if not gpas:
        return 0.0
    return sum(gpas)/len(gpas)

# -----------------------------
# Reporting
# -----------------------------

def individual_student_report(student_id, export_excel=False, excel_filename=None, export_text=False):
    student = search_student_by_id(student_id)
    if not student:
        raise ValueError('Student not found')
    grades = get_student_grades(student_id)
    # Organize by semester
    sem_map = defaultdict(list)
    for g in grades:
        sem_map[g['semester']].append(g)
    report = []
    report.append(f"Student ID: {student['student_id']}")
    report.append(f"Name: {student['first_name']} {student['last_name']}")
    report.append(f"Email: {student['email']}")
    report.append(f"DOB: {student['dob']}")
    report.append(f"Program: {student['program']}")
    report.append(f"Enrollment Year: {student['enrollment_year']}")
    report.append(f"Status: {student['status']}\n")
    for sem in sorted(sem_map.keys()):
        report.append(f"Semester: {sem}")
        report.append("Subject | Assessment | Marks | Percentage | Grade")
        for g in sem_map[sem]:
            pct = calculate_percentage(g['marks_obtained'], g['maximum_marks'])
            letter = get_letter_grade(pct)
            report.append(f"{g['subject']} | {g['assessment_type']} | {g['marks_obtained']}/{g['maximum_marks']} | {pct:.2f}% | {letter}")
        gpa = calculate_semester_gpa(student_id, sem)
        if gpa is not None:
            report.append(f"Semester GPA: {gpa:.2f}")
        report.append('')
    cgpa = calculate_cgpa(student_id)
    if cgpa is not None:
        report.append(f"CGPA: {cgpa:.2f}")
    # Export options
    if export_text:
        fn = f"{student_id}_report.txt"
        with open(fn, 'w', encoding='utf-8') as f:
            f.write('\n'.join(report))
    if export_excel:
        if openpyxl is None:
            raise RuntimeError('openpyxl not installed')
        wb = Workbook()
        ws = wb.active
        ws.title = 'Report'
        row = 1
        for line in report:
            ws.cell(row=row, column=1, value=line)
            row += 1
        if excel_filename is None:
            excel_filename = f"{student_id}_report.xlsx"
        wb.save(excel_filename)
    return '\n'.join(report)


def class_performance_report(export_excel=False, excel_filename=None):
    # Total students enrolled (status Active)
    active_students = [s for s in all_students if s.get('status','')=='Active']
    total = len(active_students)
    # Average class GPA -> average of CGPAs across active students
    cgpas = []
    for s in active_students:
        cg = calculate_cgpa(s['student_id'])
        if cg is not None:
            cgpas.append(cg)
    avg_gpa = (sum(cgpas)/len(cgpas)) if cgpas else 0.0
    # Grade distribution across all grades by letter
    dist = defaultdict(int)
    for g in all_grades:
        pct = calculate_percentage(g['marks_obtained'], g['maximum_marks'])
        letter = get_letter_grade(pct)
        dist[letter] += 1
    # Top 10 performers by CGPA
    performers = []
    for s in active_students:
        cg = calculate_cgpa(s['student_id'])
        performers.append((cg or 0.0, s))
    performers.sort(reverse=True, key=lambda x:x[0])
    top10 = performers[:10]
    report = []
    report.append(f"Total Active Students: {total}")
    report.append(f"Average Class CGPA: {avg_gpa:.2f}\n")
    report.append("Grade Distribution:")
    for letter, count in sorted(dist.items(), key=lambda x: x[0], reverse=True):
        report.append(f"{letter}: {count}")
    report.append('\nTop Performers:')
    for cg, s in top10:
        report.append(f"{s['student_id']} - {s['first_name']} {s['last_name']} : CGPA {cg:.2f}")
    if export_excel:
        if openpyxl is None:
            raise RuntimeError('openpyxl not installed')
        wb = Workbook()
        ws = wb.active
        row = 1
        for line in report:
            ws.cell(row=row, column=1, value=line)
            row += 1
        if excel_filename is None:
            excel_filename = 'class_performance_report.xlsx'
        wb.save(excel_filename)
    return '\n'.join(report)


def subject_performance_report(subject_name, export_excel=False, excel_filename=None):
    rows = [g for g in all_grades if g['subject'].lower() == subject_name.lower()]
    if not rows:
        return 'No records for subject'
    total_students = len(set(g['student_id'] for g in rows))
    avg_marks = sum(g['marks_obtained'] for g in rows) / len(rows)
    highest = max(rows, key=lambda x: x['marks_obtained'])
    lowest = min(rows, key=lambda x: x['marks_obtained'])
    pass_count = sum(1 for g in rows if calculate_percentage(g['marks_obtained'], g['maximum_marks']) >= 60)
    pass_percent = (pass_count / len(rows)) * 100
    dist = defaultdict(int)
    for g in rows:
        letter = get_letter_grade(calculate_percentage(g['marks_obtained'], g['maximum_marks']))
        dist[letter] += 1
    report = []
    report.append(f"Subject: {subject_name}")
    report.append(f"Total grade entries: {len(rows)}")
    report.append(f"Distinct students: {total_students}")
    report.append(f"Average Marks (per entry): {avg_marks:.2f}")
    report.append(f"Highest: {highest['marks_obtained']}/{highest['maximum_marks']} by {highest['student_id']}")
    report.append(f"Lowest: {lowest['marks_obtained']}/{lowest['maximum_marks']} by {lowest['student_id']}")
    report.append(f"Pass Percentage (entries >=60%): {pass_percent:.2f}%")
    report.append('Grade Distribution:')
    for k,v in sorted(dist.items(), reverse=True):
        report.append(f"{k}: {v}")
    if export_excel:
        if openpyxl is None:
            raise RuntimeError('openpyxl not installed')
        wb = Workbook()
        ws = wb.active
        row = 1
        for line in report:
            ws.cell(row=row, column=1, value=line)
            row += 1
        if excel_filename is None:
            excel_filename = f"subject_{subject_name}_report.xlsx"
        wb.save(excel_filename)
    return '\n'.join(report)


def semester_summary_report(semester_name, export_excel=False, excel_filename=None):
    rows = [g for g in all_grades if g['semester'].lower() == semester_name.lower()]
    if not rows:
        return 'No records for semester'
    students = set(g['student_id'] for g in rows)
    total_courses = len(set(g['subject'] for g in rows))
    avg_gpa = 0.0
    gpas = []
    for sid in students:
        gpa = calculate_semester_gpa(sid, semester_name)
        if gpa is not None:
            gpas.append(gpa)
    avg_gpa = sum(gpas)/len(gpas) if gpas else 0.0
    dean_list = [ (sid, calculate_semester_gpa(sid, semester_name)) for sid in students if (calculate_semester_gpa(sid, semester_name) or 0.0) >= 3.7 ]
    fails = set(g['student_id'] for g in rows if get_letter_grade(calculate_percentage(g['marks_obtained'], g['maximum_marks'])) == 'F')
    report = []
    report.append(f"Semester: {semester_name}")
    report.append(f"Total students: {len(students)}")
    report.append(f"Total courses offered: {total_courses}")
    report.append(f"Average GPA: {avg_gpa:.2f}")
    report.append('Dean\'s List:')
    for sid, gpa in dean_list:
        report.append(f"{sid} - GPA {gpa:.2f}")
    report.append(f"Failed students count: {len(fails)}")
    if export_excel:
        if openpyxl is None:
            raise RuntimeError('openpyxl not installed')
        wb = Workbook()
        ws = wb.active
        row = 1
        for line in report:
            ws.cell(row=row, column=1, value=line)
            row += 1
        if excel_filename is None:
            excel_filename = f"semester_{semester_name}_summary.xlsx"
        wb.save(excel_filename)
    return '\n'.join(report)

# -----------------------------
# Excel Import/Export helpers
# -----------------------------

def export_students_to_excel(filename='students_export.xlsx'):
    if openpyxl is None:
        raise RuntimeError('openpyxl not installed')
    wb = Workbook()
    ws = wb.active
    headers = ['student_id','first_name','last_name','email','dob','program','enrollment_year','status']
    ws.append(headers)
    for s in all_students:
        ws.append([s.get(h,'') for h in headers])
    wb.save(filename)
    return filename


def export_grades_to_excel(filename='grades_export.xlsx'):
    if openpyxl is None:
        raise RuntimeError('openpyxl not installed')
    wb = Workbook()
    ws = wb.active
    headers = ['student_id','subject','assessment_type','marks_obtained','maximum_marks','date','semester']
    ws.append(headers)
    for g in all_grades:
        ws.append([g.get(h,'') for h in headers])
    wb.save(filename)
    return filename


def import_students_from_excel(filename):
    if openpyxl is None:
        raise RuntimeError('openpyxl not installed')
    wb = openpyxl.load_workbook(filename)
    ws = wb.active
    rows = list(ws.iter_rows(values_only=True))
    headers = [str(h).strip() for h in rows[0]]
    count = 0
    for r in rows[1:]:
        data = dict(zip(headers, r))
        try:
            # minimal mapping
            sdata = {
                'student_id': data.get('student_id') or None,
                'first_name': data.get('first_name') or '',
                'last_name': data.get('last_name') or '',
                'email': data.get('email') or '',
                'dob': data.get('dob') or '',
                'program': data.get('program') or '',
                'enrollment_year': data.get('enrollment_year') or 0,
                'status': data.get('status') or 'Active'
            }
            add_student(sdata)
            count += 1
        except Exception as e:
            # continue on error
            continue
    return count


def import_grades_from_excel(filename):
    if openpyxl is None:
        raise RuntimeError('openpyxl not installed')
    wb = openpyxl.load_workbook(filename)
    ws = wb.active
    rows = list(ws.iter_rows(values_only=True))
    headers = [str(h).strip() for h in rows[0]]
    count = 0
    for r in rows[1:]:
        data = dict(zip(headers, r))
        try:
            gdata = {
                'student_id': data.get('student_id'),
                'subject': data.get('subject'),
                'assessment_type': data.get('assessment_type'),
                'marks_obtained': data.get('marks_obtained'),
                'maximum_marks': data.get('maximum_marks') or 100,
                'date': data.get('date') or '',
                'semester': data.get('semester') or ''
            }
            add_grade(gdata)
            count += 1
        except Exception:
            continue
    return count

# -----------------------------
# CLI / Menu
# -----------------------------

def input_non_empty(prompt):
    while True:
        val = input(prompt).strip()
        if val:
            return val
        print('Input cannot be empty')


def main_menu():
    while True:
        print('\n' + '='*50)
        print('STUDENT GRADE MANAGEMENT SYSTEM')
        print('='*50)
        print('1. Student Management')
        print('2. Grade Management')
        print('3. Reports')
        print('4. Import/Export Data')
        print('5. Exit')
        ch = input('Enter choice: ').strip()
        if ch == '1':
            student_menu()
        elif ch == '2':
            grade_menu()
        elif ch == '3':
            reports_menu()
        elif ch == '4':
            import_export_menu()
        elif ch == '5':
            print('Saving data and exiting...')
            save_students_to_file()
            save_grades_to_file()
            break
        else:
            print('Invalid choice')


def student_menu():
    while True:
        print('\n' + '-'*40)
        print('STUDENT MANAGEMENT')
        print('-'*40)
        print('1. Add New Student')
        print('2. Search Student')
        print('3. Update Student')
        print('4. Delete Student')
        print('5. View All Students')
        print('6. Back')
        ch = input('Enter choice: ').strip()
        if ch == '1':
            try:
                first = input_non_empty('First name: ')
                last = input_non_empty('Last name: ')
                email = input('Email: ').strip()
                dob = input_non_empty(f'DOB ({DATE_FORMAT}): ')
                program = input_non_empty('Program: ')
                enrollment_year = input_non_empty('Enrollment Year (YYYY): ')
                status = input('Status [Active]: ').strip() or 'Active'
                sdata = {
                    'first_name': first,
                    'last_name': last,
                    'email': email,
                    'dob': dob,
                    'program': program,
                    'enrollment_year': enrollment_year,
                    'status': status
                }
                sid = add_student(sdata)
                print(f'Student added with ID: {sid}')
            except Exception as e:
                print('ERROR:', e)
        elif ch == '2':
            sid = input_non_empty('Enter Student ID: ')
            s = search_student_by_id(sid)
            if not s:
                print('Student not found')
            else:
                print('\n'.join([f"{k}: {v}" for k,v in s.items()]))
                grades = get_student_grades(sid)
                print('\nGrades:')
                for g in grades:
                    pct = calculate_percentage(g['marks_obtained'], g['maximum_marks'])
                    print(f"{g['semester']} | {g['subject']} | {g['assessment_type']} | {g['marks_obtained']}/{g['maximum_marks']} | {pct:.2f}% | {get_letter_grade(pct)}")
        elif ch == '3':
            sid = input_non_empty('Enter Student ID to update: ')
            s = search_student_by_id(sid)
            if not s:
                print('Student not found')
                continue
            print('Current:', s)
            new_email = input('New email (leave blank to skip): ').strip()
            new_program = input('New program (leave blank to skip): ').strip()
            new_status = input('New status (Active/Inactive/Graduated): ').strip()
            udata = {}
            if new_email:
                udata['email'] = new_email
            if new_program:
                udata['program'] = new_program
            if new_status:
                udata['status'] = new_status
            try:
                update_student(sid, udata)
                print('Student updated')
            except Exception as e:
                print('ERROR:', e)
        elif ch == '4':
            sid = input_non_empty('Enter Student ID to delete: ')
            s = search_student_by_id(sid)
            if not s:
                print('Student not found')
                continue
            print('Student:', s)
            choice = input('Soft delete (mark inactive) or hard delete (permanent)? [soft/hard]: ').strip().lower()
            hard = (choice == 'hard')
            try:
                delete_student(sid, hard=hard)
                print('Deleted')
            except Exception as e:
                print('ERROR:', e)
        elif ch == '5':
            for s in all_students:
                print(f"{s['student_id']} | {s['first_name']} {s['last_name']} | {s['email']} | {s['status']}")
        elif ch == '6':
            break
        else:
            print('Invalid choice')


def grade_menu():
    while True:
        print('\n' + '-'*40)
        print('GRADE MANAGEMENT')
        print('-'*40)
        print('1. Add Grade Entry')
        print('2. View Student Grades')
        print('3. Update Grade')
        print('4. Delete Grade')
        print('5. Calculate GPA')
        print('6. Back')
        ch = input('Enter choice: ').strip()
        if ch == '1':
            sid = input_non_empty('Student ID: ')
            subject = input_non_empty('Subject: ')
            atype = input_non_empty('Assessment Type: ')
            marks = input_non_empty('Marks Obtained: ')
            maxm = input('Maximum Marks [100]: ').strip() or '100'
            date = input_non_empty(f'Date ({DATE_FORMAT}): ')
            semester = input_non_empty('Semester (e.g., Fall 2024): ')
            try:
                add_grade({'student_id': sid,'subject':subject,'assessment_type':atype,'marks_obtained':marks,'maximum_marks':maxm,'date':date,'semester':semester})
                print('Grade added')
            except Exception as e:
                print('ERROR:', e)
        elif ch == '2':
            sid = input_non_empty('Student ID: ')
            grades = get_student_grades(sid)
            if not grades:
                print('No grades')
            else:
                for g in grades:
                    pct = calculate_percentage(g['marks_obtained'], g['maximum_marks'])
                    print(f"{g['semester']} | {g['subject']} | {g['assessment_type']} | {g['marks_obtained']}/{g['maximum_marks']} | {pct:.2f}% | {get_letter_grade(pct)}")
        elif ch == '3':
            sid = input_non_empty('Student ID: ')
            subject = input_non_empty('Subject: ')
            atype = input_non_empty('Assessment Type: ')
            new_marks = input('New marks (leave blank to skip): ').strip()
            new_max = input('New max marks (leave blank to skip): ').strip()
            new_date = input('New date (leave blank to skip): ').strip()
            new_sem = input('New semester (leave blank to skip): ').strip()
            udata = {}
            if new_marks:
                udata['marks_obtained'] = new_marks
            if new_max:
                udata['maximum_marks'] = new_max
            if new_date:
                udata['date'] = new_date
            if new_sem:
                udata['semester'] = new_sem
            try:
                ok = update_grade(sid, subject, atype, udata)
                print('Updated' if ok else 'No matching grade found')
            except Exception as e:
                print('ERROR:', e)
        elif ch == '4':
            sid = input_non_empty('Student ID: ')
            subject = input_non_empty('Subject: ')
            atype = input_non_empty('Assessment Type: ')
            ok = delete_grade(sid, subject, atype)
            print('Deleted' if ok else 'No matching grade found')
        elif ch == '5':
            sid = input_non_empty('Student ID: ')
            semester = input_non_empty('Semester: ')
            gpa = calculate_semester_gpa(sid, semester)
            cgpa = calculate_cgpa(sid)
            if gpa is None:
                print('No grades for that semester')
            else:
                print(f'Semester GPA: {gpa:.2f}')
            if cgpa is None:
                print('No CGPA')
            else:
                print(f'CGPA: {cgpa:.2f}')
        elif ch == '6':
            break
        else:
            print('Invalid choice')


def reports_menu():
    while True:
        print('\n' + '-'*40)
        print('REPORTS')
        print('-'*40)
        print('1. Individual Student Report')
        print('2. Class Performance Report')
        print('3. Subject Performance Report')
        print('4. Semester Summary Report')
        print('5. Back')
        ch = input('Enter choice: ').strip()
        if ch == '1':
            sid = input_non_empty('Student ID: ')
            try:
                txt = individual_student_report(sid, export_text=True)
                print(txt)
                print(f'Report saved to {sid}_report.txt')
            except Exception as e:
                print('ERROR:', e)
        elif ch == '2':
            txt = class_performance_report(export_excel=True)
            print(txt)
            print('Class performance exported to class_performance_report.xlsx')
        elif ch == '3':
            subj = input_non_empty('Subject name: ')
            txt = subject_performance_report(subj)
            print(txt)
        elif ch == '4':
            sem = input_non_empty('Semester name: ')
            txt = semester_summary_report(sem)
            print(txt)
        elif ch == '5':
            break
        else:
            print('Invalid choice')


def import_export_menu():
    while True:
        print('\n' + '-'*40)
        print('IMPORT / EXPORT')
        print('-'*40)
        print('1. Export students to Excel')
        print('2. Export grades to Excel')
        print('3. Import students from Excel')
        print('4. Import grades from Excel')
        print('5. Back')
        ch = input('Enter choice: ').strip()
        if ch == '1':
            fname = input('Filename [students_export.xlsx]: ').strip() or 'students_export.xlsx'
            try:
                export_students_to_excel(fname)
                print('Exported to', fname)
            except Exception as e:
                print('ERROR:', e)
        elif ch == '2':
            fname = input('Filename [grades_export.xlsx]: ').strip() or 'grades_export.xlsx'
            try:
                export_grades_to_excel(fname)
                print('Exported to', fname)
            except Exception as e:
                print('ERROR:', e)
        elif ch == '3':
            fname = input_non_empty('Excel filename to import students from: ')
            try:
                n = import_students_from_excel(fname)
                print(f'Imported {n} student(s)')
            except Exception as e:
                print('ERROR:', e)
        elif ch == '4':
            fname = input_non_empty('Excel filename to import grades from: ')
            try:
                n = import_grades_from_excel(fname)
                print(f'Imported {n} grade(s)')
            except Exception as e:
                print('ERROR:', e)
        elif ch == '5':
            break
        else:
            print('Invalid choice')

# -----------------------------
# Initialization
# -----------------------------

def initialize():
    ensure_files()
    load_students_from_file()
    load_grades_from_file()


if __name__ == '__main__':
    initialize()
    try:
        main_menu()
    except KeyboardInterrupt:
        print('\nInterrupted. Saving data...')
        save_students_to_file()
        save_grades_to_file()
        sys.exit(0)
